import { Match } from "./match";
import { SiegeRoundResult } from "./quarterOrRound";

export const matches: Match[] = [
    {
        id: 1,
        date: new Date("2023-10-01T14:00:00"),
        team1ID: 4,
        team2ID: 2,
        team1Score: 100,
        team2Score: 95,
        hasStarted: true,
        hasFinished: true,
        timeRemaining: 0,
        quarterOrRound: 4,
        quarterOrRoundResults: [
            {team1Score: 25, team2Score: 16, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 1 scored a goal!"}]},
            {team1Score: 21, team2Score: 32, plays: [ {time: 600, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 2 scored a goal!"}]},
            {team1Score: 27, team2Score: 18, plays: [ {time: 300, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 1 scored a goal!"}]},
            {team1Score: 27, team2Score: 29, plays: [ {time: 32, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 2 scored a goal!"}]},
        ],
    },
    {
        id: 2,
        date: new Date("2023-10-02T16:00:00"),
        team1ID: 3,
        team2ID: 4,
        team1Score: 3,
        team2Score: 2,
        hasStarted: true,
        hasFinished: true,
        timeRemaining: 0,
        quarterOrRound: 4,
        quarterOrRoundResults: [
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 1 scored a goal!"}]},
            {team1Score: 1, team2Score: 1, plays: [ {time: 600, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 2 scored a goal!"}]},
            {team1Score: 1, team2Score: 0, plays: [ {time: 300, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Team 1 scored a goal!"}]},
            {team1Score: 0, team2Score: 1, plays: [ {time: 32, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Team 2 scored a goal!"}]},
        ],
    },
    {
        id: 3,
        date: new Date("2023-10-03T18:00:00"),
        team1ID: 1,
        team2ID: 2,
        team1Score: 7,
        team2Score: 5,
        hasStarted: true,
        hasFinished: false,
        timeRemaining: 134,
        quarterOrRound: 4,
        quarterOrRoundResults: [
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 1, plays: [ {time: 600, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Time Expired!"}], result: SiegeRoundResult.TEAM2_TIME},
            {team1Score: 1, team2Score: 0, plays: [ {time: 300, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Time Expired!"}], result: SiegeRoundResult.TEAM2_TIME},
            {team1Score: 0, team2Score: 1, plays: [ {time: 32, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Time Expired!"}], result: SiegeRoundResult.TEAM2_TIME},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_KILL},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_OBJ},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_OBJ},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_OBJ},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null, description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_OBJ},
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Player 1 Killed Player 2!"}], result: SiegeRoundResult.TEAM1_OBJ},
        ],
    },
    {
        id: 4,
        date: new Date("2023-10-04T20:00:00"),
        team1ID: 2,
        team2ID: 4,
        team1Score: 2,
        team2Score: 2,
        hasStarted: true,
        hasFinished: true,
        timeRemaining: 0,
        quarterOrRound: 4,
        quarterOrRoundResults: [
            {team1Score: 1, team2Score: 0, plays: [ {time: 900, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Team 1 scored a goal!"}]},
            {team1Score: 1, team2Score: 1, plays: [ {time: 600, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Team 2 scored a goal!"}]},
            {team1Score: 1, team2Score: 0, plays: [ {time: 300, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Team 1 scored a goal!"}]},
            {team1Score: 0, team2Score: 1, plays: [ {time: 32, playerActing: null, playerAssisting: null, playerEffected: null, playAction: null,description: "Team 2 scored a goal!"}]},
        ],
    },
]