import { Player } from "./player";

export const players: Player[] = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        teams: [1],
        age: 25,
        bio: "A skilled player with a passion for the game.",
        photoUrl: "https://example.com",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 2,
        teams: [2],
        firstName: "Jane",
        lastName: "Smith",
        age: 28,
        bio: "An experienced player with a strategic mindset.",
        photoUrl: "https://example.com/photo2.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 3,
        teams: [1],
        firstName: "Alice",
        lastName: "Johnson",
        age: 22,
        bio: "A rising star in the gaming community.",
        photoUrl: "https://example.com/photo3.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 4,
        teams: [2],
        firstName: "Bob",
        lastName: "Brown",
        age: 30,
        bio: "A veteran player with years of experience.",
        photoUrl: "https://example.com/photo4.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 5,
        teams: [3],
        firstName: "Charlie",
        lastName: "Davis",
        age: 27,
        bio: "A versatile player with a knack for strategy.",
        photoUrl: "https://example.com/photo5.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 6,
        teams: [3],
        firstName: "David",
        lastName: "Wilson",
        age: 26,
        bio: "A tactical player with a focus on teamwork.",
        photoUrl: "https://example.com/photo6.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 7,
        teams: [4],
        firstName: "Eve",
        lastName: "Garcia",
        age: 24,
        bio: "An agile player with quick reflexes.",
        photoUrl: "https://example.com/photo7.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    },
    {
        id: 8,
        teams: [4],
        firstName: "Frank",
        lastName: "Martinez",
        age: 29,
        bio: "A strategic player with a strong game sense.",
        photoUrl: "https://example.com/photo8.jpg",
        stats: {1: [1, 2, 3], 2: [4, 5, 6], 3: [7, 8, 9]},
    }
]