import { Team } from "./team";
import { Sport } from "./sport"

export const teams: Team[] = [
    {
        id: 0.1,
        name: "Buffalo Bills",
        sport: Sport.Football,
        logoUrl: "fb01.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Carolina Panthers",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Max Foxx",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Spider Man",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Tom Brady",
                hi_rush: "Aaron Bender",
                hi_rec: "Steven Gerrard",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Arizona Cardinals",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Luka Modric",
                hi_rush: "Karim Benzema",
                hi_rec: "Firmino",
            },
        ], // Array of match IDs
        wins: 10,
        losses: 8,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 0.2,
        name: "Atlanta Falcons",
        sport: Sport.Football,
        logoUrl: "fb02.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Cristiano",
                hi_rush: "Gareth Bale",
                hi_rec: "Bobby Charles",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Denis",
                hi_rush: "Marcelo",
                hi_rec: "Sergio Ramos",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Dani Alves",
                hi_rush: "Coutinho",
                hi_rec: "Riverie",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Mac Alister",
                hi_rush: "Paulo Dybala",
                hi_rec: "Lewandowski",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Arizona Cardinals",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Keylor Navas",
                hi_rush: "Warren",
                hi_rec: "Chelieni",
            },
        ], // Array of match IDs
        wins: 9,
        losses: 1,
        draws: 8,
        legueSubsection: "Asia",
    },
    {
        id: 0.3,
        name: "Chicago Bears",
        sport: Sport.Football,
        logoUrl: "fb03.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Neymar Jr",
                hi_rush: "Luis Suarez",
                hi_rec: "Lionel Messi",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Valverde",
                hi_rush: "Bellingham",
                hi_rec: "Vini Jr",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Kylian Mbappe",
                hi_rush: "Aaron Ramsey",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Rashford",
                hi_rush: "Smalling",
                hi_rec: "Kyle Walker",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Arizona Cardinals",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Drinkwater",
                hi_rush: "Declan Rice",
                hi_rec: "Bukayo Saka",
            },
        ], // Array of match IDs
        wins: 19,
        losses: 0,
        draws: 1,
        legueSubsection: "Europe",
    },
    {
        id: 0.4,
        name: "Arizona Cardinals",
        sport: Sport.Football,
        logoUrl: "fb04.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Dallas Cowboys",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 11,
        losses: 3,
        draws: 6,
        legueSubsection: "North America",
    },
    {
        id: 0.5,
        name: "Baltimore Ravens",
        sport: Sport.Football,
        logoUrl: "fb05.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Dallas Cowboys",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.6,
        name: "Carolina Panthers",
        sport: Sport.Football,
        logoUrl: "fb06.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "11-27",
                w_l: "13-4",
                hi_pass: "Karyy",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Cincinnati Bengals",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Dallas Cowboys",
                result: "47-22",
                w_l: "24-71",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.7,
        name: "Cincinnati Bengals",
        sport: Sport.Football,
        logoUrl: "fb07.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Cleveland Browns",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.8,
        name: "Cleveland Browns",
        sport: Sport.Football,
        logoUrl: "fb08.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Cincinnati Bengals",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Dallas Cowboys",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.9,
        name: "Dallas Cowboys",
        sport: Sport.Football,
        logoUrl: "fb09.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Houston Texans",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Denver Broncos",
                result: "21-23",
                w_l: "41-23",
                hi_pass: "Derila",
                hi_rush: "Aaron Bender",
                hi_rec: "Kanga",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Arizona Cardinals",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.10,
        name: "Denver Broncos",
        sport: Sport.Football,
        logoUrl: "fb10.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Houston Texans",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Detroit Lions",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.11,
        name: "Detroit Lions",
        sport: Sport.Football,
        logoUrl: "fb11.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Houston Texans",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 0.12,
        name: "Houston Texans",
        sport: Sport.Football,
        logoUrl: "fb12.png",
        players: [7,8], // Array of player IDs
        schedule: [
            {
                week: 1,
                date: "9/06/2025",
                opps: "Atlanta Falcons",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 2,
                date: "9/26/2025",
                opps: "Indianapolis Colts",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 3,
                date: "10/14/2025",
                opps: "Baltimore Ravens",
                result: "31-7",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 4,
                date: "11/03/2025",
                opps: "Philadelphia Eagles",
                result: "21-23",
                w_l: "13-4",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
            {
                week: 5,
                date: "11/27/2025",
                opps: "Arizona Cardinals",
                result: "47-22",
                w_l: "14-7",
                hi_pass: "Toby Mac",
                hi_rush: "Aaron Bender",
                hi_rec: "Bobby Fivvy",
            },
        ], // Array of match IDs
        wins: 4,
        losses: 10,
        draws: 6,
        legueSubsection: "Europe",
    },
    {
        id: 6,
        name: "Team A",
        sport: Sport.Basketball,
        logoUrl: "https://example.com/logoD.png",
        players: [7,8], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 9,
        losses: 6,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 7,
        name: "Team B",
        sport: Sport.Basketball,
        logoUrl: "https://example.com/logoD.png",
        players: [7,8], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 9,
        losses: 6,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 8,
        name: "Team C",
        sport: Sport.Basketball,
        logoUrl: "https://example.com/logoD.png",
        players: [7,8], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 9,
        losses: 6,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 9,
        name: "Team D",
        sport: Sport.Basketball,
        logoUrl: "https://example.com/logoD.png",
        players: [7,8], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 9,
        losses: 6,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 10,
        name: "Team E",
        sport: Sport.Basketball,
        logoUrl: "https://example.com/logoD.png",
        players: [7,8], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 9,
        losses: 6,
        draws: 2,
        legueSubsection: "South America",
    },
    {
        id: 11,
        name: "Team A",
        sport: Sport.Volleyball,
        logoUrl: "https://example.com/logoB.png",
        players: [2,4], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 8,
        losses: 7,
        draws: 2,
        legueSubsection: "Europe",
    },
    {
        id: 12,
        name: "Team B",
        sport: Sport.Volleyball,
        logoUrl: "https://example.com/logoB.png",
        players: [2,4], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 8,
        losses: 7,
        draws: 2,
        legueSubsection: "Europe",
    },
    {
        id: 13,
        name: "Team C",
        sport: Sport.Volleyball,
        logoUrl: "https://example.com/logoB.png",
        players: [2,4], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 8,
        losses: 7,
        draws: 2,
        legueSubsection: "Europe",
    },
    {
        id: 14,
        name: "Team D",
        sport: Sport.Volleyball,
        logoUrl: "https://example.com/logoB.png",
        players: [2,4], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 8,
        losses: 7,
        draws: 2,
        legueSubsection: "Europe",
    },
    {
        id: 15,
        name: "Team E",
        sport: Sport.Volleyball,
        logoUrl: "https://example.com/logoB.png",
        players: [2,4], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 8,
        losses: 7,
        draws: 2,
        legueSubsection: "Europe",
    },
    {
        id: 16,
        name: "Team A",
        sport: Sport.RainbowSixSiege,
        logoUrl: "https://example.com/logoA.png",
        players: [1,3], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 10,
        losses: 5,
        draws: 2,
        legueSubsection: "North America",
    },
    {
        id: 17,
        name: "Team B",
        sport: Sport.RainbowSixSiege,
        logoUrl: "https://example.com/logoA.png",
        players: [1,3], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 10,
        losses: 5,
        draws: 2,
        legueSubsection: "North America",
    },
    {
        id: 18,
        name: "Team C",
        sport: Sport.RainbowSixSiege,
        logoUrl: "https://example.com/logoA.png",
        players: [1,3], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 10,
        losses: 5,
        draws: 2,
        legueSubsection: "North America",
    }, 
    {
        id: 19,
        name: "Team D",
        sport: Sport.RainbowSixSiege,
        logoUrl: "https://example.com/logoA.png",
        players: [1,3], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 10,
        losses: 5,
        draws: 2,
        legueSubsection: "North America",
    }, 
    {
        id: 20,
        name: "Team E",
        sport: Sport.RainbowSixSiege,
        logoUrl: "https://example.com/logoC.png",
        players: [5,6], // Array of player IDs
        schedule: [], // Array of match IDs
        wins: 12,
        losses: 3,
        draws: 2,
        legueSubsection: "North America",
    },
    
];